path:
  generate-doc-html-dir: "/home/ubuntu/WAS/src/main/resources/static"
  SSG-root : "/home/ubuntu/static-site-generator/"

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false