path:
  generate-doc-html-dir: "/Users/hong/Desktop/hong/soma/alone/practice/saas-server/hocsserver/src/main/resources/static/"
  SSG-root: "/Users/hong/Desktop/hong/soma/alone/rander/"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test